import { writeFileSync } from "node:fs";

async function main() {
  const artifactModule = await import(
    "../contracts/artifacts/contracts/EscrowManager.sol/EscrowManager.json",
    { with: { type: "json" } }
  );
  const abi = (artifactModule.default as { abi: unknown }).abi;

  const output = `// Generated by scripts/generate-escrow-abi.ts from
// contracts/artifacts/contracts/EscrowManager.sol/EscrowManager.json --
// do not edit by hand. Re-run after any EscrowManager.sol change
// (requires contracts/ to be compiled first: cd contracts && bunx hardhat compile).
export const escrowManagerAbi = ${JSON.stringify(abi, null, 2)} as const;
`;

  writeFileSync("src/lib/chain/abi/escrow-manager.ts", output);
  console.log("Wrote src/lib/chain/abi/escrow-manager.ts");
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
